<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="P30_ManualControl" Id="{98ee4f4f-99e9-426e-9dfa-55ddf51d552b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P30_ManualControl
VAR
	i 	: INT;
	
	Temp_1_Ramping:ARRAY[1..6]OF  INT;
	Temp_1_target: ARRAY[1..6]OF  INT;
	Temp_1_BufferTarget: ARRAY[1..6]OF  INT;


	
	fbAnalogDeviceRampControl:FB_AnalogDeviceRampControl;
	

END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbAnalogDeviceRampControl();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>